top_app/views.py
from flask import Blueprint, render_template, request, flash, g, redirect, session, url_for
from ip2geotools.databases.noncommercial import DbIpCity
from OSMPythonTools.overpass import Overpass, overpassQueryBuilder
import requests
from xml.etree import ElementTree
from itertools import chain
from werkzeug.security import check_password_hash, generate_password_hash
import functools
from top_app import db, User

bp = Blueprint('home', __name__, url_prefix='/')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = db.session.query(User).filter(User.id == user_id).one()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('home.login'))

        return view(**kwargs)

    return wrapped_view

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif db.session.query(User).filter(User.username == username).count() != 0:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            u = User(username = username, password = generate_password_hash(password))
            db.session.add(u)
            db.session.commit()
            return redirect(url_for('home.login'))

        flash(error)

    return render_template('register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        try:
            user = db.session.query(User).filter(User.username == username).one()
        except:
            user = None

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('home.index'))

        flash(error)

    return render_template('login.html')

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.index'))

@bp.route('/resource_view', methods=('GET', 'POST'))
def resource_view():
    # comment out to hardcode ip address
    if request.method == 'POST':
        if request.environ.get('HTTP_X_FORWARDED_FOR') is None:
            addr = request.environ['REMOTE_ADDR']
        else:
            addr = request.environ['HTTP_X_FORWARDED_FOR'] # if behind a proxy
    #addr ="76.176.72.174"

    #addr = "98.163.214.113"       
    geocode = DbIpCity.get(addr, api_key='free')
    serv_type = request.form['service_type']
    overpass = Overpass()

    if (serv_type in ['childcare']):
        query1 = overpassQueryBuilder(bbox=[geocode.latitude-1, geocode.longitude-1, 
                                        geocode.latitude+1, geocode.longitude+1],
                                    elementType=['node','way'],
                                    selector=['"amenity"="'+str(serv_type)+'"','name'],
                                    includeGeometry=False)
        
        result1 = overpass.query(query1).toJSON()
        result1 = result1['elements']
        query2 = overpassQueryBuilder(bbox=[geocode.latitude-1, geocode.longitude-1, 
                                        geocode.latitude+1, geocode.longitude+1],
                                    elementType=['node'],
                                    selector=['"amenity"="kindergarten"','name'],
                                    includeGeometry=False)
        result2 = overpass.query(query2).toJSON()
        result2 = result2['elements']
        result0 = [result1,result2]
        result = list(chain.from_iterable(result0))
    elif (serv_type in ['place_of_worship','hospital','bank']):
        query = overpassQueryBuilder(bbox=[geocode.latitude-1, geocode.longitude-1, 
                                        geocode.latitude+1, geocode.longitude+1],
                                    elementType='node',
                                    selector=['"amenity"="'+str(serv_type)+'"','name'],
                                    includeGeometry=False)
        result = overpass.query(query).toJSON()
        result = result['elements']
    elif (serv_type in ['mental_health']):
        query = overpassQueryBuilder(bbox=[geocode.latitude-10, geocode.longitude-10, 
                                        geocode.latitude+10, geocode.longitude+10],
                                    elementType=['node','way'],
                                    selector=['"social_facility:for"="'+str(serv_type)+'"','name'],
                                    includeGeometry=False)
        result = overpass.query(query).toJSON()
        result = result['elements']
    else:
        query = overpassQueryBuilder(bbox=[geocode.latitude-1, geocode.longitude-1, 
                                        geocode.latitude+1, geocode.longitude+1],
                                    elementType=['node','way'],
                                    selector=['"office"="'+str(serv_type)+'"','name'],
                                    includeGeometry=False)
        result = overpass.query(query).toJSON()
        result = result['elements']
    
    for element in result:
        if element['type']=='way':
            apiquery = requests.get("https://api.openstreetmap.org/api/0.6/node/"+str(element['id']))
            if apiquery.content != b'':
                apitree = ElementTree.fromstring(apiquery.content)
                for child in apitree.iter('node'):
                    element['cord'] = [float(child.attrib['lon']),float(child.attrib['lat'])]
                element['type'] ='Point'
            else:
                length = len(element['nodes'])
                element['cord']=list(range(0,length))
                for idnum in range(0,length):
                    apiquery2 = requests.get("https://api.openstreetmap.org/api/0.6/node/"+str(element['nodes'][idnum]))
                    apitree2 = ElementTree.fromstring(apiquery2.content)
                    for child in apitree2.iter('node'):
                        element['cord'][idnum] = [float(child.attrib['lon']),float(child.attrib['lat'])]   
                element['type'] ='LineString'
        else:
            element['type'] ='Point'
            element['cord'] = [element['lon'],element['lat']]

    
    context = {
        "type": "FeatureCollection",
        "features": [
        {
            "type": "Feature",
            "properties" : d['tags'],
            "geometry" : {
                "type": d['type'],
                "coordinates": d['cord'],
                },
        } for d in result]
    }

    if serv_type in 'hospital':
        serv_name = 'Medical Services'
    elif serv_type in 'lawyer':
        serv_name = 'Legal Services'
    elif serv_type in 'place_of_worship':
        serv_name = 'Religous Communities'
    elif serv_type in 'mental_health':
        serv_name = 'Metal Health Services'
    else:
        serv_name = 'Child Care Services'
    
    return render_template('resource_view.html', context = context, coords = [geocode.latitude, geocode.longitude], page_name = serv_name)

@bp.route('/lookup', methods=('GET', 'POST'))
@login_required
def lookup():
    return render_template('lookup.html')

@bp.route('/tagging', methods=('GET', 'POST'))
@login_required
def tagging():
    tag_address = request.form['yes_no']
    return render_template('tagging.html', context = tag_address)

@bp.route('write_osm', methods=('GET', 'POST'))
@login_required
def write_osm():
    context = {
        'org-name' : request.form['org-name'],
        'services' : request.form['services'],
        'r-services' : request.form['r-services'],
        'website' : request.form['website'],
        'p-number' : request.form['pnumber']
    }

    # utilizing the 'osmapi' package to write to OSM servers. Package info here: https://pypi.org/project/osmapi/
    #import osmapi
    #api = osmapi.OsmApi(api="https://api06.dev.openstreetmap.org", username = u"metaodi", password = u"*******")
    #api.ChangesetCreate({u"comment": u"My first test"})
    #print(api.NodeCreate({u"lon":1, u"lat":1, u"tag": {}}))
    #api.ChangesetClose()

    return render_template('/lookup.html')

top_app/templates/base.html
<!doctype html>
<html>
    <head>
        <title>Refugee Resources</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">   
        <link href="../static/style.css" rel="stylesheet">
        <link href="../static/colors.css" rel="stylesheet">
        <link href="../static/style2.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" type="image/jpg" href="../static/images/refugee-unhcr-yellow.png"/>
        <style>
            .w3-bar-block .w3-bar-item {padding:20px}
            .w3-quarter img{margin-bottom: -6px; cursor: pointer}
            .w3-quarter img:hover{opacity: 0.6; transition: 0.3s}
        </style>
    </head>
    <body>
        <!-- Sidebar (hidden by default) -->
        <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:150px" id="mySidebar">
            <a href="javascript:void(0)" onclick="w3_close()"
            class="w3-bar-item w3-button">Find Resources</a>
            <a href="javascript:void(0)" onclick="w3_close()"
            class="w3-bar-item w3-button">For Organizations</a>
        </nav>
        <!-- Top menu -->
        <div class="w3-top">
            <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                <div class="w3-center w3-padding-16"><h1>Refugee Bridge</h1></div>
            </div>
        </div>
        {% block content %}
        {% endblock % }
        <script>
            // Script to open and close sidebar
            function w3_open() {
              document.getElementById("mySidebar").style.display = "block";
            }
             
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
            }
        </script>
    </body>
    <!--
    <hr />
    <footer align="center" id="footer">
        <p>Non-profits / Other Organizations: Click below to join out database of resources.</p>
        <img src="../static/images/non-profit.png" width="100px" height="100px">
    </footer>
    -->
</html>

top_app/templates/base2.html
<!doctype html>
<html>
    <head>
        <title>Refugee Resources</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">   
        <link href="../static/style.css" rel="stylesheet">
        <link href="../static/colors.css" rel="stylesheet">
        <link href="../static/style2.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" type="image/jpg" href="../static/images/refugee-unhcr-yellow.png"/>
        <style>
            .w3-bar-block .w3-bar-item {padding:20px}
            .w3-quarter img{margin-bottom: -6px; cursor: pointer}
            .w3-quarter img:hover{opacity: 0.6; transition: 0.3s}
        </style>
    </head>
    <body>
        <!-- Sidebar (hidden by default) -->
        <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:150px" id="mySidebar">
            <a href="javascript:void(0);" onclick="w3_close()"
            class="w3-bar-item w3-button">&#x2715;</a>
            <a href="/" onclick="w3_close()"
            class="w3-bar-item w3-button">Find Resources</a>
            <a href="/lookup" onclick="w3_close()"
            class="w3-bar-item w3-button">For Organizations</a>
            <div class="w3-bottom">
                {% if g.user %}
                <span class="w3-bar-item w3-button">User: {{ g.user['username'] }}</span>
                <a href="{{ url_for('home.logout') }}" class="w3-bar-item w3-button">Log Out</a>
                {% else %}
                    <a href="{{ url_for('home.register') }}" class="w3-bar-item w3-button">Register</a>
                    <a href="{{ url_for('home.login') }}" class="w3-bar-item w3-button">Log In</a>
                {% endif %}
            </div>
        </nav>
        <!-- Top menu -->
        <div class="w3-top">
            <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                <div class="w3-center w3-padding-16"><h1>{% block header %}{% endblock %}</h1></div>
            </div>
        </div>
        <div class="w3-main w3-content" style="max-width:1200px;margin-top:100px"></div>
            <div class="w3-row-padding w3-padding-16 w3-center" id="login-row-1"></div>
                {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
                {% endfor %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <script>
            // Script to open and close sidebar
            function w3_open() {
              document.getElementById("mySidebar").style.display = "block";
            }
             
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
            }
        </script>
    </body>
</html>

top_app/templates/index.html
<!doctype html>
<html>
    <head>
        <title>Refugee Resources</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">   
        <link href="../static/style.css" rel="stylesheet">
        <link href="../static/colors.css" rel="stylesheet">
        <link href="../static/style2.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" type="image/jpg" href="../static/images/refugee-unhcr-yellow.png"/>
        <style>
            .w3-bar-block .w3-bar-item {padding:20px}
            .w3-quarter img{margin-bottom: -6px; cursor: pointer}
            .w3-quarter img:hover{opacity: 0.6; transition: 0.3s}
        </style>
        <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    </head>
    <body>
        <div id="mobilemenu">
            <!-- Top Navigation Menu -->
            <div class="topnav">
                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </a>
                <a href="/" class="active"><h1>Refugee Assist</h1></a>
             <!-- Navigation links (hidden by default) -->
            <div id="myLinks">
                <a href="/">Find Resources</a>
                <a href="/lookup">Add an Organization</a>
                {% if g.user %}
                    <span class="w3-bar-item w3-button">User: {{ g.user['username'] }}</span>
                    <a href="{{ url_for('home.logout') }}" class="w3-bar-item w3-button">Log Out</a>
                {% endif %}
            </div>
            <!-- "Hamburger menu" / "Bar icon" to toggle the navigation links -->
            </div>
        </div>
        <div id="desktopmenu">
            <!-- Sidebar (hidden by default) -->
            <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:150px" id="mySidebar">
                <a href="javascript:void(0);" onclick="w3_close()"
                class="w3-bar-item w3-button">&#x2715;</a>
                <a href="/" onclick="w3_close()"
                class="w3-bar-item w3-button">Find Resources</a>
                <a href="/lookup" onclick="w3_close()"
                class="w3-bar-item w3-button">For Organizations</a>
                <div class="w3-bottom">
                    {% if g.user %}
                    <span class="w3-bar-item w3-button">User: {{ g.user['username'] }}</span>
                    <a href="{{ url_for('home.logout') }}" class="w3-bar-item w3-button">Log Out</a>
                    {% else %}
                        <a href="{{ url_for('home.register') }}" class="w3-bar-item w3-button">Register</a>
                        <a href="{{ url_for('home.login') }}" class="w3-bar-item w3-button">Log In</a>
                    {% endif %}
                </div>
            </nav>
            <!-- Top menu -->
            <div class="w3-top">
                <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                    <div class="w3-center w3-padding-16"><h1>Refugee Assist</h1></div>
                </div>
            </div>
        </div>

        
        <!-- !PAGE CONTENT! -->
        <div class="w3-main w3-content" id="icon-container" style="max-width:1200px;">
            <p id="description">Click on the icons below to find a service nearest you.</p>
            <div class="w3-row-padding w3-padding-16 w3-center" id="services-row-1">
                <div class="w3-third button">
                    <form method="POST" action="/resource_view">
                        <button class="w3-button w3-padding-16" id="medical-button" value="hospital" name="service_type">
                            <img src="../static/images/hospital-ward-symbol.png" alt="Medical" class="fill-vertical fill-horizontal service-icon">
                            <p>Medical</p>
                        </button>
                    </form>
                </div>
                <div class="w3-third button">
                    <form method="POST" action="/resource_view">
                        <button class="w3-button w3-padding-16" id="legal-button" value="lawyer" name="service_type">
                            <img src="../static/images/legal_2.png" alt="Legal" class="fill-vertical fill-horizontal service-icon">
                            <p>Legal</p>
                        </button>
                    </form>
                </div>
                <div class="w3-third button">
                    <form method="POST" action="/resource_view">
                        <button class="w3-button w3-padding-16" id="religion-button" value="place_of_worship" name="service_type">
                            <img src="../static/images/religion-2.png" alt="Religious" class="fill-vertical fill-horizontal service-icon">
                            <p>Religious</p>
                        </button>
                    </form>
                </div>
            </div>
            <div class="w3-row-padding w3-padding-16 w3-center" id="services-row-2">
                <div class="w3-third button">
                    <form method="POST" action="/resource_view">
                        <button class="w3-button w3-padding-16" id="social-button" value="mental_health" name="service_type">
                            <img src="../static/images/mental-health.png" alt="Mental Health" class="fill-vertical fill-horizontal service-icon">
                             <p>Mental Health</p>
                        </button>
                    </form>
                </div>
                <div class="w3-third">
                    <form method="POST" action="/resource_view">
                        <button class="w3-button w3-padding-16" id="childcare-button" value="childcare" name="service_type">
                               <img src="../static/images/childcare.png" alt="Childcare" class="fill-vertical fill-horizontal service-icon">
                               <p>Childcare</p>
                        </button>
                    </form>
                </div>
                <div class="w3-third">
                    <!--<form method="POST" action="/resource_view">-->
                        <button class="w3-button w3-padding-16" id="bank-button" value="" name="service_type">
                            <img src="../static/images/bank.png" alt="Other" class="fill-vertical fill-horizontal service-icon">
                            <p>Banking</p>
                        </button>
                    <!--</form>-->
                </div>
            </div>  
        </div>
        <script>
                // Script to open and close sidebar
                function w3_open() {
                document.getElementById("mySidebar").style.display = "block";
                }
                
                function w3_close() {
                document.getElementById("mySidebar").style.display = "none";
                }
                /* Toggle between showing and hiding the navigation menu links when the user clicks on the hamburger menu / bar icon */
                function myFunction() {
                    var x = document.getElementById("myLinks");
                    if (x.style.display === "block") {
                        x.style.display = "none";
                    } else {
                        x.style.display = "block";
                    }
                }
        </script>
    </body>
    <!--
    <hr />
    <footer align="center" id="footer">
        <p>Non-profits / Other Organizations: Click below to join out database of resources.</p>
        <img src="../static/images/non-profit.png" width="100px" height="100px">
    </footer>
    -->
</html>

top_app/templates/login.html
{% extends 'base2.html' %}

{% block header %}
  <h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Log In">
  </form>
{% endblock %}

top_app/templates/register.html
{% extends 'base2.html' %}

{% block header %}
<h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
  <label for="username">Username</label>
  <input name="username" id="username" required>
  <label for="password">Password</label>
  <input type="password" name="password" id="password" required>
  <input type="submit" value="Register">
</form>
{% endblock %}

top_app/templates/resource_view.html
<!doctype html>
<html>
    <head>
        <title>Refugee Resources</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">   
        <link href="../static/style.css" rel="stylesheet">
        <link href="../static/colors.css" rel="stylesheet">
        <link href="../static/style2.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&display=swap" rel="stylesheet">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="shortcut icon" type="image/jpg" href="../static/images/refugee-unhcr-yellow.png"/>
        <style>
            .w3-bar-block .w3-bar-item {padding:20px}
            .w3-quarter img{margin-bottom: -6px; cursor: pointer}
            .w3-quarter img:hover{opacity: 0.6; transition: 0.3s}
        </style>
        <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin="">
        </script>
    </head>
    <body>
        <div id="mobilemenu">
            <!-- Top Navigation Menu -->
            <div class="topnav">
                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </a>
                <a href="/" class="active"><h1>Refugee Assist</h1></a>
                <div class="w3-center">
                    <h2>{{ page_name }}</h2>
                </div>
                
             <!-- Navigation links (hidden by default) -->
            <div id="myLinks">
                <a href="/">Find Resources</a>
                <a href="/">Add an Organization</a>
                {% if g.user %}
            <span class="w3-bar-item w3-button">User: {{ g.user['username'] }}</span>
            <a href="{{ url_for('home.logout') }}" class="w3-bar-item w3-button">Log Out</a>
          {% endif %}
            </div>
            <!-- "Hamburger menu" / "Bar icon" to toggle the navigation links -->
            
            </div>
        </div>
        <div id="desktopmenu">
            <!-- Sidebar (hidden by default) -->
            <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:150px" id="mySidebar">
                <a href="javascript:void(0);" onclick="w3_close()"
                class="w3-bar-item w3-button">&#x2715;</a>
                <a href="/" onclick="w3_close()" class="w3-bar-item w3-button">Find Resources</a>
                <a href="/lookup" onclick="w3_close()" class="w3-bar-item w3-button">For Organizations</a>
                <div class="w3-bottom">
                    {% if g.user %}
                    <span class="w3-bar-item w3-button">User: {{ g.user['username'] }}</span>
                    <a href="{{ url_for('home.logout') }}" class="w3-bar-item w3-button">Log Out</a>
                    {% else %}
                        <a href="{{ url_for('home.register') }}" class="w3-bar-item w3-button">Register</a>
                        <a href="{{ url_for('home.login') }}" class="w3-bar-item w3-button">Log In</a>
                    {% endif %}
                </div>
            </nav>
            <!-- Top menu -->
            <div class="w3-top">
                <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
                    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
                    <div class="w3-center w3-padding-16"><h1>Refugee Assist</h1></div>
                    <div class="w3-center w3-padding-16">
                        <h2>{{ page_name }}</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="w3-main w3-content" style="max-width:1200px;">
            <div class="w3-center w3-padding-16">
                <p style="font-size: 16px; font-family: 'Lato', sans-serif; color: #000;">See below for services in your area.</p>
                <div id="mapid"></div>
            </div>
        </div>
        <script>
            // Script to open and close sidebar
            function w3_open() {
              document.getElementById("mySidebar").style.display = "block";
            }
             
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
            }
            /* Toggle between showing and hiding the navigation menu links when the user clicks on the hamburger menu / bar icon */
            function myFunction() {
                var x = document.getElementById("myLinks");
                if (x.style.display === "block") {
                    x.style.display = "none";
                } else {
                    x.style.display = "block";
                }
            }
            
        </script>
        <script type="text/javascript">
            var mymap = L.map('mapid').setView([ {{ coords[0] }}, {{ coords[1] }} ], 11);
            L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                    '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                    'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                id: 'mapbox/streets-v11',
                tileSize: 512,
                zoomOffset: -1
            }).addTo(mymap);
            
            var data = JSON.parse('{{ context | tojson | safe }}');
            function onEachFeature(feature, layer) {
                var popupContent = "<strong>Name: </strong>"+feature.properties['name']+"<br> <strong>Amenity: </strong>"+feature.properties['amenity']+"<br> <strong>Address: </strong>"+feature.properties['addr:housenumber']+" "+feature.properties['addr:street']+"<br>"+feature.properties['addr:city']+" "+feature.properties['addr:postcode'] + "<br> <a href='https://www.google.com/maps/search/?api=1&query=" + feature.geometry['coordinates'][1] + "," + feature.geometry['coordinates'][0] +"'><strong>Find this on Google Maps.</strong></a>";
                layer.bindPopup(popupContent);
            }
            var myLayer = L.geoJSON(data,{onEachFeature: onEachFeature}).addTo(mymap);
            
        </script>
       

    </body>
</html>